### ISSUE TITLE
Move to JuliaPerf

### ISSUE THREAD

**Issue by carstenbauer** [JuliaPerf/PAPI.jl#3]
Perhaps it would make sense to move this to https://github.com/JuliaPerf at some point.

**Comment by carstenbauer** [comment]
Hey Tom, I'd like to follow up on this. Given that we also have [LIKWID.jl](https://github.com/JuliaPerf/LIKWID.jl) over at JuliaPerf I think it would be nice to have PAPI.jl there as well. Shall we make the move?

(cc @vchuravy)

**Comment by vchuravy** [comment]
I invited Tom to JuliaPerf so that he can move the repo if he so wishes

**Comment by tomhaber** [comment]
I've transferred ownership
